name: Experiment
on: 
  schedule:
  - cron: '*/5 * * * *'

jobs:
  job1:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    # - name: Git checkout
    #   uses: actions/checkout@v2
    #   with: { ref: debug }
    # --label "$LABELS"
    - name: List files
      run: ls
    - name: Create team sync issue
      run: gh issue create --title "$TITLE" --assignee "$ASSIGNEES"  --body "$BODY"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_REPO: ${{ github.repository }}
        TITLE: Team sync
        ASSIGNEES: hafro05,nprime496
        LABELS: weekly sync,docs-team
        BODY: |
          Hello @hafro05,

          I hope this message finds you well! I wanted to extend an invitation your way. You've been selected to present either in an upcoming meeting or contribute an article for our group. We greatly value your expertise and would love to hear your thoughts on a subject you're passionate about.
          
          Would you kindly propose a topic that resonates with you and let us know if you'd prefer to present it in a meeting or as an article? Your input will be highly appreciated, and we're looking forward to learning from your insights.
          
          Thank you in advance for your contribution!
          
          Best regards
        PINNED: false
        CLOSE_PREVIOUS: false
